import Head from 'next/head'
import { Inter } from 'next/font/google'
import style from '@/styles/login.module.scss'
import { useRouter } from "next/router"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter()
  const loginBtnEvent = () => {
    // Login API 처리 이후에 성공했으면 localStroate에 AccessToken 넘기고 /cms로 이동
    router.push('/cms')
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div className={style.loginPageWrap}>
          <div className={style.loginWrap}>
            <div className={style.loginItem}>
              <input type="email" placeholder='input your id' className='form-control'></input>
            </div>
            <div className={style.loginItem}>
              <input type="password" placeholder='input your password.' className='form-control'></input>
            </div>
            <div>
              <button className='btn btn-primary' onClick={loginBtnEvent}>로그인</button>
            </div>
          </div>

        </div>
      </main>
    </>
  )
}
